"""change len-s

Revision ID: 1511a83fdc3c
Revises: 43fb948fa219
Create Date: 2024-06-20 03:49:21.092315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1511a83fdc3c'
down_revision: Union[str, None] = '43fb948fa219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)
    # ### end Alembic commands ###
